Compalny.R.PL/ViewModels/UserViewModel.cs
namespace Compalny.R.PL.ViewModels
{
	public class UserViewModel
	{
		public string Id {  get; set; }

		public string FirstName {  get; set; }

		public string LastName { get; set; }

		public string Email { get; set; }

		public IEnumerable<string> Roles { get; set; }

	}
}

Compalny.R.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Compalny.R.PL.ViewModels;
using Company.R.BLL;
using Company.R.BLL.Interfaces;
using Company.R.DAL.Models;
using Microsoft.AspNetCore.Mvc;

namespace Compalny.R.PL.Controllers
{
    public class EmployeeController : Controller
    {
        //private IEmployeeRepository _EmployeeRepository;
        //private IDepartmentRepository _DepartmentRepository;
        //public EmployeeController(IEmployeeRepository EmployeeRepository,
        //    IDepartmentRepository departmentRepository)
        //{
        //    _EmployeeRepository = EmployeeRepository;
        //    _DepartmentRepository = departmentRepository;
        //}

        private readonly IUnitOfWork _IunitOfWork;
        private readonly IMapper _mapper;
        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _IunitOfWork = unitOfWork;
            _mapper = mapper;
        }
        //public IActionResult Index(string name)
        //{
        //    var employees = Enumerable.Empty<Employee>();
        //    if (name == null)
        //    {
        //        employees = _IunitOfWork.EmployeeRepository.GetAll().ToList();
        //        return View(employees);
        //    }
        //    else
        //    {
        //        employees = _IunitOfWork.EmployeeRepository.getDataSearch(name);
        //        return View(employees);
        //    }

        //}


        //public IActionResult Index(string name)
        //{
        //    var employees = Enumerable.Empty<Employee>();
        //    if (name == null)
        //    {
        //        employees = _IunitOfWork.EmployeeRepository.GetAll().ToList();

        //    }
        //    else
        //    {
        //        employees = _IunitOfWork.EmployeeRepository.getDataSearch(name);

        //    }
        //    //var result = _mapper.Map<IEnumerator<EmployeeViewModel>>(employees);
        //    return View(employees);

        //    //var result = _mapper.Map<IEnumerator<EmployeeViewModel>>(employees);
        //    //return View(result);
        //}


        public IActionResult Index(string name)
        {
            var employees = Enumerable.Empty<Employee>();

            if (name == null)
            {
                employees = _IunitOfWork.EmployeeRepository.GetAll().ToList();

            }
            else
            {
                employees = _IunitOfWork.EmployeeRepository.getDataSearch(name);

            }
            //var result = _mapper.Map<IEnumerator<EmployeeViewModel>>(employees);
            return View(employees);

            //var result = _mapper.Map<IEnumerator<EmployeeViewModel>>(employees);
            //return View(result);
        }



        [HttpGet]
        public IActionResult Add()
        {
            ViewData["Department"] = _IunitOfWork.DepartmentRepository.GetAll();
            return View();
        }

        //[HttpPost]
        //[AutoValidateAntiforgeryToken]
        //public IActionResult Add(Employee employee)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var count = _IunitOfWork.EmployeeRepository.Add(employee);
        //        if (count > 0)
        //        {
        //            return RedirectToAction(nameof(Index));
        //        }

        //    }
        //    return View(employee);

        //}


        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Add(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                employee.ImageName = Helper.UploadFile(employee.Image, "Images");

                var emp = _mapper.Map<Employee>(employee);

                var count = _IunitOfWork.EmployeeRepository.Add(emp);
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }

            }
            return View(employee);

        }

        public IActionResult Details(int? id, string Viewname = "Details")
        {
            if (id is null) return BadRequest();

            var department = _IunitOfWork.EmployeeRepository.GetByID(id.Value);

            if (department is null) return NotFound();
            return View(Viewname, department);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewData["Department"] = _IunitOfWork.DepartmentRepository.GetAll();

            var emp = _IunitOfWork.EmployeeRepository.GetByID(id);
            return View(emp);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]

        public IActionResult Edit([FromRoute] int id, Employee employee)
        {

            if (id != employee.Id)
            {
                return BadRequest();
            }


            //employee.IsDelete = false;
            if (ModelState.IsValid)
            {

                if (employee.ImageName is not null)
                {
                    Helper.DeleteFile(employee.ImageName, "Images");
                }
                var count = _IunitOfWork.EmployeeRepository.Update(employee);
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }


            return View(employee);
        }



        [HttpGet]
        public IActionResult Delete(int id)

        {
          var emp= _IunitOfWork.EmployeeRepository.GetByID(id);
            return View(emp);

        }
        [HttpPost]
        public IActionResult Delete([FromRoute] int id, Employee emp)

        {
            //if (id == emp.Id) return BadRequest();

            if (ModelState.IsValid)
            {
                var count = _IunitOfWork.EmployeeRepository.Delete(emp);
                if (count > 0)
                {
                    Helper.DeleteFile(emp.ImageName,"Images");
                    return RedirectToAction(nameof(Index));

                }
            }
            return View(emp);
        }
    }
}

Compalny.R.PL/Controllers/UserController.cs
using Compalny.R.PL.ViewModels;
using Company.R.DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Compalny.R.PL.Controllers
{
	public class UserController : Controller
	{
		public UserManager<ApplicationUser> _UserManager;
        public UserController(UserManager<ApplicationUser> UserManager)
        {
            _UserManager = UserManager;
        }
        public async Task<IActionResult> Index(string search)
		{
			var user =Enumerable.Empty<UserViewModel>();
			if (string.IsNullOrEmpty(search))
			{
				user = await _UserManager.Users.Select(x=> new UserViewModel()
				{
					Email=x.Email,
					FirstName=x.Firstname,
					LastName=x.Lastname,
					Id=x.Id,
					Roles=_UserManager.GetRolesAsync(x).Result
				}).ToListAsync();
			}
			else
			{
				user = await _UserManager.Users.Where(x=>x.Email.ToLower().Contains(search
					.ToLower())).Select(x=> new UserViewModel()
					{
						Email = x.Email,
						FirstName = x.Firstname,
						LastName = x.Lastname,
						Id = x.Id,
						Roles = _UserManager.GetRolesAsync(x).Result
					}).ToListAsync();
			}
			return View(user);
		}


		public async Task<IActionResult>Details(string id,string viewname = "Details") 
		{
			if (id is null) return BadRequest();
			var user= await _UserManager.FindByIdAsync(id);
			if(user is null){
				return NotFound();
			}
			var users = new UserViewModel()
			{
				Email = user.Email,
				FirstName = user.Firstname,
				LastName = user.Lastname,
				Id = user.Id,
				Roles = _UserManager.GetRolesAsync(user).Result
			};
			return View(viewname,users);
		}
		[HttpGet]
		public async Task<IActionResult> Edit(string ?id) {
			return await Details(id,"Edit");
		}
		[HttpPost]
        public async Task<IActionResult> Edit([FromRoute]string? id,UserViewModel userViewModel)
        {
			if(id != userViewModel.Id) { return BadRequest(); }
			if(ModelState.IsValid)
			{
				var user = await _UserManager.FindByIdAsync(id);
				if(user is null){
					return NotFound();
				}
				user.Firstname = userViewModel.FirstName;
				user.Lastname = userViewModel.LastName;
				user.Email = userViewModel.Email;

				await _UserManager.UpdateAsync(user);
				return RedirectToAction(nameof(Index));
			}
            return View(userViewModel);
        }

		[HttpGet]
		public async Task<IActionResult>Delete(string id)
		{
			return await Details(id,"Delete");
		}

		public async Task<IActionResult> Delete([FromRoute] string id,UserViewModel userViewModel)
		{
            if (id != userViewModel.Id)
			{
				return BadRequest();
			}
            if (ModelState.IsValid)
            {
                var user = await _UserManager.FindByIdAsync(id);
                if (user is null)
                {
                    return NotFound();
                }
                
                await _UserManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));
            }
            return View(userViewModel);
        }



    }

}

Compalny.R.PL/Views/User/Delete.cshtml
@using Compalny.R.PL.ViewModels
@model UserViewModel
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>







<h1>Delete</h1>
<form asp-action="Delete">


    <div>
        <div class="form-group">
            <label asp-for="Id" class="col-form-label"></label>
            <input readonly asp-for="Id" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="FirstName" class="col-form-label"></label>
            <input readonly asp-for="FirstName" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="LastName" class="col-form-label"></label>
            <input readonly asp-for="LastName" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Email" class="col-form-label"></label>
            <input readonly asp-for="Email" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Roles" class="col-form-label"></label>
            <input readonly asp-for="Roles" class="form-control" />
        </div>



        <a asp-controller="User" asp-action="Index" class="btn btn-light">Back To List</a>
    </div>





    <input type="submit" value="Delete" class="btn btn-danger" />


    <a asp-controller="User" asp-action="Index" class="btn btn-light">Back To List</a>
</form>

Compalny.R.PL/Views/User/Details.cshtml
@using Compalny.R.PL.ViewModels
@model UserViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>




@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<div>
    <div class="form-group">
        <label asp-for="Id" class="col-form-label"></label>
        <input readonly asp-for="Id" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="FirstName" class="col-form-label"></label>
        <input readonly asp-for="FirstName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="LastName" class="col-form-label"></label>
        <input readonly asp-for="LastName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Email" class="col-form-label"></label>
        <input readonly asp-for="Email" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Roles" class="col-form-label"></label>
        <input readonly asp-for="Roles" class="form-control" />
    </div>








    <a asp-controller="User" asp-action="Index" class="btn btn-light">Back To List</a>
</div>

Compalny.R.PL/Views/User/Edit.cshtml
@using Compalny.R.PL.ViewModels
@model UserViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Edit</h1>




<form asp-action="Edit">


    <div class="form-group">
        <label asp-for="FirstName" class="col-form-label"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>


    <div class="form-group">
        <label asp-for="LastName" class="col-form-label"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>


    <div class="form-group">
        <label asp-for="Email" class="col-form-label"></label>
        <input asp-for="Email" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Roles" class="col-form-label"></label>
        <input asp-for="Roles" class="form-control" />
    </div>

    







    <input type="submit" value="Save" class="btn btn-primary" />
    <a asp-controller="User" asp-action="Index" class="btn btn-light">Back To List</a>
</form>

@section validation {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Compalny.R.PL/Views/User/Index.cshtml
@using Compalny.R.PL.ViewModels
@model IEnumerable<UserViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
@if (Model.Count() > 0)
{
    <table class="table table-striped table-hover">
        <thead>
            <tr>
               
                <th>@Html.DisplayNameFor(D => D.Id)</th>
                <th>@Html.DisplayNameFor(D => D.FirstName)</th>
                <th>@Html.DisplayNameFor(D => D.LastName)</th>
                <th>@Html.DisplayNameFor(D => D.Email)</th>
                <th>@Html.DisplayNameFor(D => D.Roles)</th>
                <th>Details</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td>
                        @user.Id
                    </td>
                    <td>
                        @user.FirstName
                    </td>
                     <td>
                        @user.LastName
                    </td>
                    <td>
                        @user.Email
                    </td>
                    <td>
                        @string.Join(" ",user.Roles)
                    </td>

                    <td>
                        <a asp-controller="Employee" asp-action="Details" asp-route-id="@user.Id" class="btn btn-warning">
                            <i class="fas fa-eye"></i> Details
                        </a>
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@user.Id" class="btn btn-success">
                            <i class="fas fa-edit"></i> Update
                        </a>
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-id="@user.Id" class="btn btn-danger">
                            <i class="fas fa-trash"></i> Delete
                        </a>
                    </td>
                </tr>
             
            }
        </tbody>
    </table>

}
else
{
    <div class="mt-4 alert alert-warning">
        <h4>There is No User :(</h4>
    </div>
}