Compalny.R.PL/ViewModels/RoleViewModel.cs
namespace Compalny.R.PL.ViewModels
{
    public class RoleViewModel
    {
        public string id {  get; set; }
        public string RoleName {  get; set; }
    }
}

Compalny.R.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Compalny.R.PL.ViewModels;
using Company.R.BLL;
using Company.R.BLL.Interfaces;
using Company.R.DAL.Models;
using Microsoft.AspNetCore.Mvc;

namespace Compalny.R.PL.Controllers
{
    public class EmployeeController : Controller
    {
        //private IEmployeeRepository _EmployeeRepository;
        //private IDepartmentRepository _DepartmentRepository;
        //public EmployeeController(IEmployeeRepository EmployeeRepository,
        //    IDepartmentRepository departmentRepository)
        //{
        //    _EmployeeRepository = EmployeeRepository;
        //    _DepartmentRepository = departmentRepository;
        //}

        private readonly IUnitOfWork _IunitOfWork;
        private readonly IMapper _mapper;
        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _IunitOfWork = unitOfWork;
            _mapper = mapper;
        }
        //public IActionResult Index(string name)
        //{
        //    var employees = Enumerable.Empty<Employee>();
        //    if (name == null)
        //    {
        //        employees = _IunitOfWork.EmployeeRepository.GetAll().ToList();
        //        return View(employees);
        //    }
        //    else
        //    {
        //        employees = _IunitOfWork.EmployeeRepository.getDataSearch(name);
        //        return View(employees);
        //    }

        //}


        //public IActionResult Index(string name)
        //{
        //    var employees = Enumerable.Empty<Employee>();
        //    if (name == null)
        //    {
        //        employees = _IunitOfWork.EmployeeRepository.GetAll().ToList();

        //    }
        //    else
        //    {
        //        employees = _IunitOfWork.EmployeeRepository.getDataSearch(name);

        //    }
        //    //var result = _mapper.Map<IEnumerator<EmployeeViewModel>>(employees);
        //    return View(employees);

        //    //var result = _mapper.Map<IEnumerator<EmployeeViewModel>>(employees);
        //    //return View(result);
        //}


        public IActionResult Index(string name)
        {
            var employees = Enumerable.Empty<Employee>();

            if (name == null)
            {
                employees = _IunitOfWork.EmployeeRepository.GetAll().ToList();

            }
            else
            {
                employees = _IunitOfWork.EmployeeRepository.getDataSearch(name);

            }
            //var result = _mapper.Map<IEnumerator<EmployeeViewModel>>(employees);
            return View(employees);

            //var result = _mapper.Map<IEnumerator<EmployeeViewModel>>(employees);
            //return View(result);
        }



        [HttpGet]
        public IActionResult Add()
        {
            ViewData["Department"] = _IunitOfWork.DepartmentRepository.GetAll();
            return View();
        }

        //[HttpPost]
        //[AutoValidateAntiforgeryToken]
        //public IActionResult Add(Employee employee)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var count = _IunitOfWork.EmployeeRepository.Add(employee);
        //        if (count > 0)
        //        {
        //            return RedirectToAction(nameof(Index));
        //        }

        //    }
        //    return View(employee);

        //}


        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Add(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                employee.ImageName = Helper.UploadFile(employee.Image, "Images");

                var emp = _mapper.Map<Employee>(employee);

                var count = _IunitOfWork.EmployeeRepository.Add(emp);
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }

            }
            return View(employee);

        }

        public IActionResult Details(int? id, string Viewname = "Details")
        {
            if (id is null) return BadRequest();

            var department = _IunitOfWork.EmployeeRepository.GetByID(id.Value);

            if (department is null) return NotFound();
            return View(Viewname, department);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewData["Department"] = _IunitOfWork.DepartmentRepository.GetAll();

            var emp = _IunitOfWork.EmployeeRepository.GetByID(id);
            return View(emp);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]

        public IActionResult Edit([FromRoute] int id, Employee employee)
        {

            if (id != employee.Id)
            {
                return BadRequest();
            }


            //employee.IsDelete = false;
            if (ModelState.IsValid)
            {

                if (employee.ImageName is not null)
                {
                    Helper.DeleteFile(employee.ImageName, "Images");
                }
                var count = _IunitOfWork.EmployeeRepository.Update(employee);
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }


            return View(employee);
        }



        [HttpGet]
        public IActionResult Delete(int id)

        {
          var emp= _IunitOfWork.EmployeeRepository.GetByID(id);
            return View(emp);

        }
        [HttpPost]
        public IActionResult Delete([FromRoute] int id, Employee emp)

        {
            //if (id == emp.Id) return BadRequest();

            if (ModelState.IsValid)
            {
                var count = _IunitOfWork.EmployeeRepository.Delete(emp);
                if (count > 0)
                {
                    Helper.DeleteFile(emp.ImageName,"Images");
                    return RedirectToAction(nameof(Index));

                }
            }
            return View(emp);
        }
    }
}

Compalny.R.PL/Controllers/RoleController.cs
using Compalny.R.PL.ViewModels;
using Company.R.DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace Compalny.R.PL.Controllers
{
    public class RoleController : Controller
    {
        public RoleManager<IdentityRole> _RoleManager;
        public UserManager<ApplicationUser> _UserManager ;
        public RoleController(RoleManager<IdentityRole> RoleManager,UserManager<ApplicationUser>userManager)
        {
            _RoleManager = RoleManager;
            _UserManager = userManager;
        }
        public async Task<IActionResult> Index(string search)
        {
            var role = Enumerable.Empty<RoleViewModel>();
            if (string.IsNullOrEmpty(search))
            {
                role = await _RoleManager.Roles.Select(x => new RoleViewModel()
                {
                   id = x.Id,
                   RoleName=x.Name
                }).ToListAsync();
            }
            else
            {
                role = await _RoleManager.Roles.Where(x => x.Name.ToLower().Contains(search
                    .ToLower())).Select(x => new RoleViewModel()
                    {
                        
                        id = x.Id,
                        RoleName = x.Name
                    }).ToListAsync();
            }
            return View(role);
        }


        public async Task<IActionResult> Details(string id, string viewname = "Details")
        {
            if (id is null) return BadRequest();
            var role = await _RoleManager.FindByIdAsync(id);
            if (role is null)
            {
                return NotFound();
            }
            var roles = new RoleViewModel()
            {
                id=role.Id,
                RoleName=role.Name
            };
            return View(viewname, role);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id, "Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] string? id, RoleViewModel roleViewModel)
        {
            if (id != roleViewModel.id) { return BadRequest(); }
            if (ModelState.IsValid)
            {
                var role = await _RoleManager.FindByIdAsync(id);
                if (role is null)
                {
                    return NotFound();
                }
                role.Name = roleViewModel.RoleName;
               

                await _RoleManager.UpdateAsync(role);
                return RedirectToAction(nameof(Index));
            }
            return View(roleViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        public async Task<IActionResult> Delete([FromRoute] string id, RoleViewModel userViewModel)
        {
            if (id != userViewModel.id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                var user = await _RoleManager.FindByIdAsync(id);
                if (user is null)
                {
                    return NotFound();
                }

                await _RoleManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));
            }
            return View(userViewModel);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel roleViewModel)
        {
            if(ModelState.IsValid)
            {
                var role = new IdentityRole() { Name=roleViewModel.RoleName
                
                };
            await    _RoleManager.CreateAsync(role);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddOrRemove(string roleid)
        {
            var role=await _RoleManager.FindByIdAsync(roleid);
            if (role is null)
            {
                return NotFound();
            }
            ViewData["RoleId"] = roleid;
            var userInRole = new List<UserInRoleViewModel>();
            var user=await _UserManager.Users.ToListAsync();

            foreach (var useritem in user)
            {
                var usInRol = new UserInRoleViewModel()
                {
                    UserId = useritem.Id,

                    UserName = useritem.UserName
                };
                if (await _UserManager.IsInRoleAsync(useritem,role.Name))
                    {
                    usInRol.IsSelectes = true;
                }
                else
                {
                    usInRol.IsSelectes = false;

                }
                userInRole.Add(usInRol);
            }
            
            return View(userInRole);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemove(string roleid,List<UserInRoleViewModel> userInRoleViewModels)
        {
            var role = await _RoleManager.FindByIdAsync(roleid);
            if (role is null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                foreach (var item in userInRoleViewModels)
                {
                    var appuser = await _UserManager.FindByIdAsync(item.UserId);
                    if (item.IsSelectes && ! await _UserManager.IsInRoleAsync(appuser,role.Name))
                    {
                      await  _UserManager.AddToRoleAsync(appuser,role.Name);
                    }else if (item.IsSelectes && await _UserManager.IsInRoleAsync(appuser, role.Name))
                    {
                       await _UserManager.RemoveFromRoleAsync(appuser, role.Name);

                    }
                }
                return RedirectToAction(nameof(Edit),new { id=roleid});


            }
            return View(userInRoleViewModels);
        }

    }
}

Compalny.R.PL/Views/Role/AddOrRemove.cshtml
@using Compalny.R.PL.ViewModels
@model List<UserInRoleViewModel>
@{
    ViewData["Title"] = "AddOrRemove";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var roleid= ViewData["RoleId"] as string;
}

<form asp-action="AddOrRemove" asp-route-id="@roleid">
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="form-group">
            <input asp-for="@Model[i].IsSelectes" />
            <label asp-for="@Model[i].IsSelectes">@Model[i].UserName</label>
        </div>
        <input type="hidden" asp-for="@Model[i].UserId" />
        <input type="hidden" asp-for="@Model[i].UserName" />

    }
    <input type="submit" value="Update" class="btn btn-danger"/>
    <input type="submit" asp-route-id="@roleid" value="Edit" class="btn btn-light" />

</form>

Compalny.R.PL/Views/Role/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using Compalny.R.PL.ViewModels


@model RoleViewModel
@{
    ViewData["Title"] = "Add";
}



<h2>Create Role</h2>

<form asp-action="create" enctype="multipart/form-data">
    

    <div class="form-group">
        <label asp-for="RoleName" class="col-form-label"></label>
        <input asp-for="RoleName" class="form-control" />
        <span asp-validation-for="RoleName" class="text-danger"></span>
    </div>



   

    <input type="submit" value="Create" class="btn btn-primary" />
    <a asp-controller="Role" asp-action="Index" class="btn btn-light">Back To List</a>
</form>

Compalny.R.PL/Views/Role/Delete.cshtml
@using Compalny.R.PL.ViewModels
@model RoleViewModel
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>





<h1>Delete</h1>
<form asp-action="Delete">


    <div>
        <div class="form-group">
            <label asp-for="id" class="col-form-label"></label>
            <input readonly asp-for="id" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="RoleName" class="col-form-label"></label>
            <input readonly asp-for="RoleName" class="form-control" />
        </div>

     



        <a asp-controller="Role" asp-action="Index" class="btn btn-light">Back To List</a>
    </div>





    <input type="submit" value="Delete" class="btn btn-danger" />


    <a asp-controller="Role" asp-action="Index" class="btn btn-light">Back To List</a>
</form>

Compalny.R.PL/Views/Role/Details.cshtml
@using Compalny.R.PL.ViewModels
@model RoleViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>











<div>
    <div class="form-group">
        <label asp-for="id" class="col-form-label"></label>
        <input readonly asp-for="id" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="RoleName" class="col-form-label"></label>
        <input readonly asp-for="RoleName" class="form-control" />
    </div>

   







    <a asp-controller="Role" asp-action="Index" class="btn btn-light">Back To List</a>
</div>

Compalny.R.PL/Views/Role/Edit.cshtml
@using Compalny.R.PL.ViewModels
@model RoleViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>










<form asp-action="Edit">


    <div class="form-group">
        <label asp-for="id" class="col-form-label"></label>
        <input asp-for="id" class="form-control" />
        <span asp-validation-for="id" class="text-danger"></span>
    </div>


    <div class="form-group">
        <label asp-for="RoleName" class="col-form-label"></label>
        <input asp-for="RoleName" class="form-control" />
        <span asp-validation-for="RoleName" class="text-danger"></span>
    </div>


  




    <a asp-action="AddOrRemove" asp-route-roleid="@Model.id" class="btn btn-dark">Add Or Remove</a>



    <input type="submit" value="Save" class="btn btn-primary" />
    <a asp-controller="Role" asp-action="Index" class="btn btn-light">Back To List</a>
</form>

@section validation {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Compalny.R.PL/Views/Role/Index.cshtml
@using Compalny.R.PL.ViewModels
@model IEnumerable<RoleViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>




@if (Model.Count() > 0)
{
    <table class="table table-striped table-hover">
        <thead>
            <tr>

                <th>@Html.DisplayNameFor(D => D.id)</th>
                <th>@Html.DisplayNameFor(D => D.RoleName)</th>
               
                <th>Details</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var role in Model)
            {
                <tr>
                    <td>
                        @role.id
                    </td>
                    <td>
                        @role.RoleName
                    </td>
                    

                    <td>
                        <a asp-controller="Employee" asp-action="Details" asp-route-id="@role.id" class="btn btn-warning">
                            <i class="fas fa-eye"></i> Details
                        </a>
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@role.id" class="btn btn-success">
                            <i class="fas fa-edit"></i> Update
                        </a>
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-id="@role.id" class="btn btn-danger">
                            <i class="fas fa-trash"></i> Delete
                        </a>
                    </td>
                </tr>

            }
        </tbody>
    </table>

}
else
{
    <div class="mt-4 alert alert-warning">
        <h4>There is No Role :(</h4>
    </div>
}